onerror resume
wave tags  sim
wave update off
wave zoom range 0 1
wave group tb_comparacion_3p_vs_4p_portable_python -backgroundcolor #004466
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.MAGNITUD_WIDTH -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.N -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PI -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.DT -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.ADC_SCALE -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.ENABLE_ADC3_NOISE -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.numero_medidas -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.ADC3_NOISE_SIGMA_LSB -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_CONT_MIN -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_CONT_RANGO_MEDIDA -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_CONT_AMP_BARRIDO -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.MICRO_F1_HZ -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.MICRO_F2_HZ -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_C1_MICRO_PCT -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.CP_MICRO_PCT -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.VERBOSE -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.clk125 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.dds_bus -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc1_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc2_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc3_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc3_data_4p_noisy -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc1_data_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.adc2_data_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.areset_n -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.start -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.medida -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.test1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.test2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.test3 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.salto -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.numero_rep -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.numero_ciclos -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.numero_anchura -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.ADC_A -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.ADC_B -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.DAC_A -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.incrementado -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fin -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fin2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.VALID_M -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.VALID_P -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.DAC_S_registrado -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.MODULO -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.MODULO2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.address_mem -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.address_mem2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.address_mem3 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.estado_pasos_cero -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASE -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASEA -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASEB -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASE2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASEA2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.PHASEB2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.autoshunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.cuantificacion -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_ext -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_int -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.C_mem -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_shunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_contact1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.R_contact2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.C_p1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.C_p2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_cont_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_cont_base_medida -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_cont_delta_barrido -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_c1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_c2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.cp_val -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.r_c1_base_medida -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.cp_base_medida -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.t_inicio_medida_s -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.rext_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.rint_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.c_mem_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.k_degradacion -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.seed -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.seed_adc3_noise -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_gen -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.f_actual -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fase_acc -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_c_mem -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.i_total -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_tejido -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.i_int -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.node_re_p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.node_re_n -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.node_shunt_high -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_a_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_b_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_c_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.mag_z_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fase_z_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_mag_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_fase_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.den_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_a_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_bc_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.mag_z_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fase_z_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_mag_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_fase_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.den_3p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.modulo_4p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fase_4p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_mag_4p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_fase_4p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.modulo_3p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.fase_3p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_mag_3p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.error_fase_3p_corr -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.filas_guardadas -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.z_bio_re -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.z_bio_im -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.z_bio_mag -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.z_bio_fase -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.omega -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.xc -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.den_bio -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.v_shunt_effective_authosunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python tb_comparacion_3p_vs_4p_portable_python.clk65 -tag sim -radix hexadecimal
wave insertion [expr [wave index insertpoint] + 1]
wave update on
wave top 0
