onerror resume
wave tags  sim
wave update off
wave zoom range 0 202138588000
wave group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit -backgroundcolor #004466
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.R_contact1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.R_contact2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.C_p1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.C_p2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.R_ext -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.R_int -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.C_mem -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.R_shunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.clk -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dds_bus -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.cuantificacion -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.senoide -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.autoshunt_value -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.r_cont_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.c_contact1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.rext_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.rint_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.c_mem_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_a_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_b_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_c_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.adc1_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.adc2_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.adc3_data_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_dac_out -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_dac_out.v {-radix hexadecimal -select} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_dac_out.i {-radix hexadecimal -select} } -select
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_adc1 -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_adc2 -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.node_adc3 -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_dac_4p -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_dac_aplicado -tag sim -radix string -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_dac_aplicado.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.v_dac_aplicado.i {-radix hexadecimal} }
wave insertion [expr [wave index insertpoint] + 1]
wave group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p -backgroundcolor #006666
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.R_contact1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.R_contact2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.C_p1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.C_p2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.R_ext -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.R_int -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.C_mem -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.R_shunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.v_dac_val -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.clk -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.r_cont_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.c_contact1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.autoshunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.rext_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.rint_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.c_mem_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.node_adc1 -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.node_adc2 -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.node_adc3 -tag sim -radix string
wave insertion [expr [wave index insertpoint] + 1]
wave group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p -backgroundcolor #226600
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.BITS -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.VREF -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.R_OUT -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.data_i -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.clk -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.node_out -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.node_out.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.node_out.i {-radix hexadecimal} }
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.v_target -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.dac_internal -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.dac_internal.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.dac_internal.i {-radix hexadecimal} }
wave insertion [expr [wave index insertpoint] + 1]
wave group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage -backgroundcolor #666600
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage.R -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage.p -tag sim -radix string
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.dac4p.r_output_stage.n -tag sim -radix string
wave insertion [expr [wave index insertpoint] + 1]
wave group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype -backgroundcolor #004466
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_gen -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_gen.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_gen.i {-radix hexadecimal} }
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc1 -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc1.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc1.i {-radix hexadecimal} }
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc2 -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc2.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc2.i {-radix hexadecimal} }
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc3 -tag sim -radix string -expand -subitemconfig { tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc3.v {-radix hexadecimal} tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.node_adc3.i {-radix hexadecimal} }
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.r_s1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.r_s2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.c_p1 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.c_p2 -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.r_shunt -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.rext_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.rint_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.c_mem_instant -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.clk -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.DT -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.v_cmem_s -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.v_cp1_s -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.v_cp2_s -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.i_total -tag sim -radix hexadecimal
wave add -group tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype tb_comparacion_3p_vs_4p_portable_python_nettype.analog_circuit.analog_4p.bioz_inst_nettype.v_gen -tag sim -radix hexadecimal
wave insertion [expr [wave index insertpoint] + 1]
wave update on
wave top 72
